"""empty message

Revision ID: 207b6c879a2b
Revises: 706ed41668c6
Create Date: 2023-04-04 21:55:34.502778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207b6c879a2b'
down_revision = '706ed41668c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
