"""empty message

Revision ID: 33deb8b015e9
Revises: 0958ec45534e
Create Date: 2023-04-04 23:43:33.706583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33deb8b015e9'
down_revision = '0958ec45534e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.drop_column('trash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
