"""empty message

Revision ID: 373826d0f192
Revises: e7d431d6b47e
Create Date: 2023-05-04 14:42:42.871019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373826d0f192'
down_revision = 'e7d431d6b47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_given', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('like_given')

    op.drop_table('stats')
    # ### end Alembic commands ###
