"""empty message

Revision ID: 48f35677aad4
Revises: fd125c32522e
Create Date: 2023-04-13 01:16:45.415876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48f35677aad4'
down_revision = 'fd125c32522e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.drop_column('id2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id2', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
