"""empty message

Revision ID: 69825ac4e6b5
Revises: 03f3980f8d56
Create Date: 2023-04-08 20:23:48.378087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69825ac4e6b5'
down_revision = '03f3980f8d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrive_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queue', schema=None) as batch_op:
        batch_op.drop_column('arrive_time')

    # ### end Alembic commands ###
