"""empty message

Revision ID: 7437434b34af
Revises: 69825ac4e6b5
Create Date: 2023-04-08 20:24:02.659684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7437434b34af'
down_revision = '69825ac4e6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queue', schema=None) as batch_op:
        batch_op.alter_column('arrive_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queue', schema=None) as batch_op:
        batch_op.alter_column('arrive_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
