"""empty message

Revision ID: 79b7d39c767d
Revises: 43f9afbc121b
Create Date: 2023-04-13 14:19:47.674584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b7d39c767d'
down_revision = '43f9afbc121b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dark_theme', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_dark_theme')

    # ### end Alembic commands ###
