"""empty message

Revision ID: c03051ba358c
Revises: 
Create Date: 2024-04-06 13:56:44.122445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03051ba358c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.Column('name_to_print', sa.String(length=30), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('like_given', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('queue',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_index', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Enum('clear', 'close', 'open', name='taskenum'), nullable=False),
    sa.Column('execute_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_task_execute_time'), ['execute_time'], unique=False)

    op.create_table('user_queue',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.String(length=10), nullable=False),
    sa.Column('name_printed', sa.String(length=30), nullable=False),
    sa.Column('index_in_queue', sa.Integer(), nullable=False),
    sa.Column('arrive_time', sa.DateTime(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'queue_id', 'index_in_queue')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_queue')
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_task_execute_time'))

    op.drop_table('queue_task')
    op.drop_table('queue')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('stats')
    # ### end Alembic commands ###
