"""empty message

Revision ID: fd125c32522e
Revises: 88f231e08322
Create Date: 2023-04-13 01:16:35.693570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd125c32522e'
down_revision = '88f231e08322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_task', schema=None) as batch_op:
        batch_op.drop_column('id2')

    # ### end Alembic commands ###
